# Generated by Django 3.0 on 2020-05-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(verbose_name='都道府県コード')),
                ('name', models.CharField(max_length=10, verbose_name='都道府県名')),
                ('name_en', models.CharField(max_length=20, verbose_name='都道府県名(英語)')),
            ],
            options={
                'verbose_name': '県',
                'verbose_name_plural': '県',
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients', models.PositiveIntegerField(default=0, verbose_name='感染者数')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='死者数')),
                ('date', models.DateField(db_index=True, verbose_name='日付')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.Prefecture')),
            ],
            options={
                'verbose_name': '日別統計',
                'verbose_name_plural': '日別統計',
                'unique_together': {('prefecture', 'date')},
            },
        ),
    ]
