# Generated by Django 3.0.6 on 2020-05-07 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField(db_index=True, verbose_name='報告日付')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(verbose_name='都道府県コード')),
                ('name', models.CharField(max_length=10, verbose_name='都道府県名')),
                ('name_en', models.CharField(max_length=20, verbose_name='都道府県名(英語)')),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': '都道府県',
            },
        ),
        migrations.CreateModel(
            name='BehaviorStats',
            fields=[
                ('basestats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.BaseStats')),
                ('restraint_ratio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='自粛率')),
            ],
            options={
                'verbose_name': '行動統計',
                'verbose_name_plural': '行動統計',
            },
            bases=('stats.basestats',),
        ),
        migrations.CreateModel(
            name='InfectionStats',
            fields=[
                ('basestats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.BaseStats')),
                ('patients', models.PositiveIntegerField(default=0, verbose_name='感染者数')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='死者数')),
            ],
            options={
                'verbose_name': '感染統計',
                'verbose_name_plural': '感染統計',
            },
            bases=('stats.basestats',),
        ),
        migrations.AddField(
            model_name='basestats',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.Prefecture'),
        ),
        migrations.AlterUniqueTogether(
            name='basestats',
            unique_together={('prefecture', 'reported_date')},
        ),
    ]
