# Generated by Django 3.0 on 2020-05-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefecture',
            options={'verbose_name': '都道府県', 'verbose_name_plural': '都道府県'},
        ),
        migrations.RenameField(
            model_name='dailystats',
            old_name='date',
            new_name='reported_date',
        ),
        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together={('prefecture', 'reported_date')},
        ),
    ]
