# Generated by Django 3.0.6 on 2020-05-15 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20200513_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infectionstats',
            old_name='death',
            new_name='total_death',
        ),
        migrations.RenameField(
            model_name='infectionstats',
            old_name='recovered',
            new_name='total_recovered',
        ),
        migrations.AddField(
            model_name='infectionstats',
            name='restraint_ratio',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='自粛率'),
        ),
    ]
