# Generated by Django 3.0.6 on 2020-05-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20200516_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectionstats',
            name='current_infected',
            field=models.IntegerField(default=0, verbose_name='現在感染者数'),
        ),
        migrations.AlterField(
            model_name='infectionstats',
            name='total_death',
            field=models.IntegerField(default=0, verbose_name='死者数'),
        ),
        migrations.AlterField(
            model_name='infectionstats',
            name='total_infected',
            field=models.IntegerField(default=0, verbose_name='累計感染者数'),
        ),
        migrations.AlterField(
            model_name='infectionstats',
            name='total_recovered',
            field=models.IntegerField(default=0, verbose_name='回復者数'),
        ),
    ]
